services:
    sharelatex:
        restart: always
        image: code.lcpu.dev/lcpu/sharelatex:main
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
            latex-ocr-ui:
                condition: service_started
            latex-ocr-api:
                condition: service_started
        ports:
            - 5000:80
        links:
            - mongo
            - redis
        volumes:
            - /opt/volumes/sharelatex/data:/var/lib/overleaf
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            OVERLEAF_APP_NAME: PKU LaTeX
            OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
            OVERLEAF_REDIS_HOST: redis
            REDIS_HOST: redis
            ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
            ENABLE_CONVERSIONS: 'true'
            EMAIL_CONFIRMATION_DISABLED: 'true'
            TEXMFVAR: /var/lib/overleaf/tmp/texmf-var
            OVERLEAF_BEHIND_PROXY: 'true'
            OVERLEAF_SECURE_COOKIE: 'true'
            OVERLEAF_SITE_URL: https://latex.pku.edu.cn/
            OVERLEAF_NAV_TITLE: PKU LaTeX
            OVERLEAF_HEADER_IMAGE_URL: https://latex.pku.edu.cn/img/pkutex-white.svg
            OVERLEAF_ADMIN_EMAIL: 'lcpu@pku.edu.cn'
            OVERLEAF_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://lcpu.club\">PKU Linux Club</a>. Sponsored by <a href=\"https://osslab-pku.github.io\">OSS-lab @ PKU-SEI</a> and PKU ITS."},{"text":"<a href=\"https://github.com/lcpu-club/remotex\">GitHub repo</a>"} ]'
            OVERLEAF_RIGHT_FOOTER: '[{"text": "v0.0.2, system updated"} ]'
            OVERLEAF_SITE_LANGUAGE: 'zh-CN'
            TEX_LIVE_DOCKER_IMAGE: "code.lcpu.dev/lcpu/sharelatex-base:2024"
            ALL_TEX_LIVE_DOCKER_IMAGES: "code.lcpu.dev/lcpu/sharelatex-base:2024"
            OVERLEAF_IS_SERVER_PRO: true
            SANDBOXED_COMPILES_HOST_DIR: '/opt/volumes/sharelatex/data/data/compiles'

    mongo:
        restart: always
        image: docker.smirrors.lcpu.dev/library/mongo:5
        container_name: mongo
        ports:
            - 127.0.0.1:27017:27017
        volumes:
            - /opt/volumes/sharelatex/mongo:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: always
        image: docker.smirrors.lcpu.dev/library/redis:6.2
        container_name: redis
        expose:
            - 6379
        volumes:
            - /opt/volumes/sharelatex/redis:/data

    latex-ocr-ui:
        restart: always
        image: code.lcpu.dev/lcpu/latex-ocr-ui:main
        container_name: latex-ocr-ui
    
    latex-ocr-api:
        restart: always
        image: docker.smirrors.lcpu.dev/lukasblecher/pix2tex:api
        container_name: latex-ocr-api